spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 39987654lh
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: KolokolovEgorVladimirovichBKS2201
  expiration: 3600000